name: Merge V2Ray Configs

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and merge config files
        run: |
          FILES=(
            "https://raw.githubusercontent.com/ThomasJasperthecat/sub/main/sublist1.txt"
            "https://raw.githubusercontent.com/V2RAYCONFIGSPOOL/V2RAY_SUB/refs/heads/main/v2ray_configs_no1.txt"
            "https://raw.githubusercontent.com/V2RAYCONFIGSPOOL/V2RAY_SUB/refs/heads/main/v2ray_configs_no2.txt"
            "https://raw.githubusercontent.com/V2RAYCONFIGSPOOL/V2RAY_SUB/refs/heads/main/v2ray_configs_no3.txt"
            "https://raw.githubusercontent.com/V2RAYCONFIGSPOOL/V2RAY_SUB/refs/heads/main/v2ray_configs_no4.txt"
            "https://raw.githubusercontent.com/V2RAYCONFIGSPOOL/V2RAY_SUB/refs/heads/main/v2ray_configs_no5.txt"
            "https://raw.githubusercontent.com/ShatakVPN/ConfigForge-V2Ray/main/configs/light.txt"                                      
            "https://raw.githubusercontent.com/Mosifree/-FREE2CONFIG/refs/heads/main/Reality#Aleph%20%E2%9D%A4%F0%9F%A4%8D%F0%9F%92%9A%20FREE2CONFIG"
          )
          > merged_config.txt
          for url in "${FILES[@]}"; do
            curl -s "$url" >> merged_config.txt
            echo "" >> merged_config.txt
          done

      - name: Encode to Base64
        run: |
          base64 -w0 merged_config.txt > merged_config_temp.txt
          mv merged_config_temp.txt merged_config.txt

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ -n $(git status -s) ]]; then
            git add merged_config.txt
            git commit -m "Auto-merge configs: $(date -u)"
            git push
          fi
