name: Merge V2Ray Configs

on:
  schedule:
    # Runs every 15 minutes
    - cron: '*/15 * * * *'
  # Allows you to run it manually from the Actions tab
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and merge config files
        run: |
        
          FILES=(
            "https://raw.githubusercontent.com/ThomasJasperthecat/sub/main/sublist1.txt"
            "https://raw.githubusercontent.com/iboxz/free-v2ray-collector/main/main/mix"
            "https://raw.githubusercontent.com/V2RAYCONFIGSPOOL/V2RAY_SUB/refs/heads/main/v2ray_configs_no1.txt"
            "https://raw.githubusercontent.com/V2RAYCONFIGSPOOL/V2RAY_SUB/refs/heads/main/v2ray_configs_no2.txt"
            "https://raw.githubusercontent.com/V2RAYCONFIGSPOOL/V2RAY_SUB/refs/heads/main/v2ray_configs_no3.txt"
            "https://raw.githubusercontent.com/V2RAYCONFIGSPOOL/V2RAY_SUB/refs/heads/main/v2ray_configs_no4.txt"
            "https://raw.githubusercontent.com/V2RAYCONFIGSPOOL/V2RAY_SUB/refs/heads/main/v2ray_configs_no5.txt"
            "https://raw.githubusercontent.com/ShatakVPN/ConfigForge-V2Ray/main/configs/light.txt"
          )

          # Create an empty file (or clear it if it exists)
          > merged_config.txt

          # Download each file and add it to the final file
          for url in "${FILES[@]}"; do
            echo "Downloading $url..."
            curl -s "$url" >> merged_config.txt
            # Add an empty line to separate each config
            echo "" >> merged_config.txt
          done

          echo "All configs merged into merged_config.txt"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
        
          if [[ -n $(git status -s) ]]; then
            git add merged_config.txt
            git commit -m "Auto-merge configs: $(date -u)"
            git push
          else
            echo "No changes to commit."
          fi
